title: Filoran
email: 4881@schravenlant.nl
description: A website for our fictive country Filoran
baseurl: ""
url: "https://filoran.fi"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

permalink: /:path/:basename
